"""Daily real_perf summary email (DAILY-REAL-PERF-EMAIL, 2026-05-25).

Wraps scripts/real_perf_split_by_source.py — captures the analysis output,
formats as HTML, and sends via Resend. Wired into scheduler at 23:30 UTC
(after settlement so yesterday's bets are scored).

The summary contains:
  * Total settled bets / staked / PnL / ROI
  * Split by source (auto-placer vs manual /admin/place)
  * Per-bot rollup
  * Per-market rollup
  * Anomaly callouts (large slippage, single-bot ROI swings)

Goal: wake up to "yesterday looked X" without having to run the script
manually. Especially useful during the 2-week paper-only validation
window (2026-05-25 → 2026-06-07) where the verdict depends on the
day-over-day pattern.

Env vars (re-used):
  RESEND_API_KEY      Resend API key (also used by email_digest)
  DIGEST_FROM_EMAIL   sender (default: "OddsIntel <digest@oddsintel.app>")
  ADMIN_ALERT_EMAIL   recipient (same address as health_alerts)
"""
from __future__ import annotations
import io
import os
import sys
import subprocess
from contextlib import redirect_stdout
from datetime import date
from pathlib import Path

from rich.console import Console

console = Console()

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
FROM_EMAIL = os.getenv("DIGEST_FROM_EMAIL", "OddsIntel <digest@oddsintel.app>")
ADMIN_ALERT_EMAIL = os.getenv("ADMIN_ALERT_EMAIL", "")


def _capture_split_by_source(days: int = 1) -> str:
    """Run real_perf_split_by_source.py and capture stdout as a string.
    Uses subprocess so we don't have to import-side-effect the script."""
    repo_root = Path(__file__).resolve().parent.parent.parent
    script = repo_root / "scripts" / "real_perf_split_by_source.py"
    if not script.exists():
        return f"(script not found: {script})"
    try:
        result = subprocess.run(
            [sys.executable, str(script), "--days", str(days)],
            cwd=str(repo_root),
            capture_output=True,
            text=True,
            timeout=120,
        )
        out = result.stdout or ""
        if result.returncode != 0:
            out += f"\n[exit {result.returncode}]\n{result.stderr[-500:]}"
        return out
    except Exception as e:
        return f"(capture error: {e})"


def _format_html(yesterday_summary: str, last_7d_summary: str) -> str:
    """Wrap the captured CLI output in minimal HTML with monospace font."""
    today = date.today().isoformat()
    return f"""<!doctype html>
<html><body style="font-family: -apple-system, sans-serif; max-width: 800px; padding: 16px;">
<h2>OddsIntel — daily real-perf summary ({today})</h2>
<h3>Yesterday (1 day)</h3>
<pre style="background:#f4f4f4;padding:12px;overflow-x:auto;font-family:Menlo,monospace;font-size:12px;">
{yesterday_summary.replace('<', '&lt;').replace('>', '&gt;')}
</pre>
<h3>Last 7 days</h3>
<pre style="background:#f4f4f4;padding:12px;overflow-x:auto;font-family:Menlo,monospace;font-size:12px;">
{last_7d_summary.replace('<', '&lt;').replace('>', '&gt;')}
</pre>
<p style="color:#888;font-size:11px;">
Generated by workers/jobs/daily_real_perf_email.py — DAILY-REAL-PERF-EMAIL.
Source split: <code>placer</code> = auto-placer (--record),
<code>manual</code> = /admin/place modal.
</p>
</body></html>"""


def _send_via_resend(subject: str, html: str) -> bool:
    if not RESEND_API_KEY or not ADMIN_ALERT_EMAIL:
        console.print(f"[yellow]daily_real_perf_email: no Resend creds — skipping. Subject: {subject}[/yellow]")
        return False
    import httpx
    try:
        resp = httpx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {RESEND_API_KEY}", "Content-Type": "application/json"},
            json={"from": FROM_EMAIL, "to": [ADMIN_ALERT_EMAIL], "subject": subject, "html": html},
            timeout=15,
        )
        if resp.status_code in (200, 201):
            console.print(f"[green]daily_real_perf_email sent: {subject}[/green]")
            return True
        console.print(f"[yellow]Resend status {resp.status_code}: {resp.text[:200]}[/yellow]")
        return False
    except Exception as e:
        console.print(f"[yellow]Resend error: {e}[/yellow]")
        return False


def send_daily_real_perf() -> None:
    """Entry point for scheduler. Captures yesterday + last 7d summaries and
    emails them. Idempotent — running twice in a day sends two emails (the
    receiver's deduplication is on the receiving end, not ours)."""
    console.print("[cyan]daily_real_perf_email: capturing yesterday + 7d split[/cyan]")
    yesterday = _capture_split_by_source(days=1)
    last_7d = _capture_split_by_source(days=7)
    html = _format_html(yesterday, last_7d)
    subject = f"OddsIntel daily real-perf — {date.today().isoformat()}"
    _send_via_resend(subject, html)


if __name__ == "__main__":
    send_daily_real_perf()
