-- ============================================================
-- Migration 047: Remove Kambi Duplicate Leagues, Teams, Fixtures
-- ============================================================
-- Generated by workers/scripts/detect_duplicates.py
-- Kambi scraper removed 2026-05-06. This cleans up the DB records
-- it created that duplicate API-Football canonical records.
--
-- SAFE TO RE-RUN: all UPDATEs are idempotent (WHERE old_id has no
-- effect once rows are already re-pointed).

BEGIN;

-- ============================================================
-- 1. Merge Kambi duplicate leagues into AF canonical
-- ============================================================

-- Brazil / Catarinense 2 (1 matches) → Brazil / Catarinense - 2
UPDATE matches        SET league_id = 'bf78e916-9201-4bf3-8f74-cd69bec02c66' WHERE league_id = '999a2b14-2821-4acd-a34d-09382ba1a2f1';
UPDATE seasons        SET league_id = 'bf78e916-9201-4bf3-8f74-cd69bec02c66' WHERE league_id = '999a2b14-2821-4acd-a34d-09382ba1a2f1';
UPDATE model_evaluations SET league_id = 'bf78e916-9201-4bf3-8f74-cd69bec02c66' WHERE league_id = '999a2b14-2821-4acd-a34d-09382ba1a2f1';
DELETE FROM leagues   WHERE id = '999a2b14-2821-4acd-a34d-09382ba1a2f1';

-- Brazil / Paulista A4 (3 matches) → Brazil / Paulista - A4
UPDATE matches        SET league_id = '55f487eb-9384-424a-a47e-f7272a81a296' WHERE league_id = '16f585bf-a3dd-468d-9ed7-7a8ca6899f49';
UPDATE seasons        SET league_id = '55f487eb-9384-424a-a47e-f7272a81a296' WHERE league_id = '16f585bf-a3dd-468d-9ed7-7a8ca6899f49';
UPDATE model_evaluations SET league_id = '55f487eb-9384-424a-a47e-f7272a81a296' WHERE league_id = '16f585bf-a3dd-468d-9ed7-7a8ca6899f49';
DELETE FROM leagues   WHERE id = '16f585bf-a3dd-468d-9ed7-7a8ca6899f49';

-- Czech Republic / 1. Liga U19 (7 matches) → Czech-Republic / 1. Liga U19
UPDATE matches        SET league_id = 'c32f7c72-ae2f-45d0-bf62-695fa70eb6d3' WHERE league_id = '4b8ea47f-0cc3-4d9d-b29d-27b43277f2fd';
UPDATE seasons        SET league_id = 'c32f7c72-ae2f-45d0-bf62-695fa70eb6d3' WHERE league_id = '4b8ea47f-0cc3-4d9d-b29d-27b43277f2fd';
UPDATE model_evaluations SET league_id = 'c32f7c72-ae2f-45d0-bf62-695fa70eb6d3' WHERE league_id = '4b8ea47f-0cc3-4d9d-b29d-27b43277f2fd';
DELETE FROM leagues   WHERE id = '4b8ea47f-0cc3-4d9d-b29d-27b43277f2fd';

-- England / National League North (4 matches) → England / National League - North
UPDATE matches        SET league_id = '37742a92-d719-4574-b1a3-3132ee7b2c3f' WHERE league_id = '362be0ed-2a98-41b3-8dc0-25e5e490776d';
UPDATE seasons        SET league_id = '37742a92-d719-4574-b1a3-3132ee7b2c3f' WHERE league_id = '362be0ed-2a98-41b3-8dc0-25e5e490776d';
UPDATE model_evaluations SET league_id = '37742a92-d719-4574-b1a3-3132ee7b2c3f' WHERE league_id = '362be0ed-2a98-41b3-8dc0-25e5e490776d';
DELETE FROM leagues   WHERE id = '362be0ed-2a98-41b3-8dc0-25e5e490776d';

-- England / National League South (4 matches) → England / National League - South
UPDATE matches        SET league_id = 'b4df8f40-ab54-40ea-ab95-f04f4f658ed1' WHERE league_id = '078fdc47-f683-476a-9182-589999643a8c';
UPDATE seasons        SET league_id = 'b4df8f40-ab54-40ea-ab95-f04f4f658ed1' WHERE league_id = '078fdc47-f683-476a-9182-589999643a8c';
UPDATE model_evaluations SET league_id = 'b4df8f40-ab54-40ea-ab95-f04f4f658ed1' WHERE league_id = '078fdc47-f683-476a-9182-589999643a8c';
DELETE FROM leagues   WHERE id = '078fdc47-f683-476a-9182-589999643a8c';

-- Finland / Kakkonen Lohko B (1 matches) → Finland / Kakkonen - Lohko B
UPDATE matches        SET league_id = '2c06986e-42a0-43bf-9afd-46dda25969a5' WHERE league_id = 'd25f6f67-9f64-4669-b060-f367264df571';
UPDATE seasons        SET league_id = '2c06986e-42a0-43bf-9afd-46dda25969a5' WHERE league_id = 'd25f6f67-9f64-4669-b060-f367264df571';
UPDATE model_evaluations SET league_id = '2c06986e-42a0-43bf-9afd-46dda25969a5' WHERE league_id = 'd25f6f67-9f64-4669-b060-f367264df571';
DELETE FROM leagues   WHERE id = 'd25f6f67-9f64-4669-b060-f367264df571';

-- France / National 2 Group A (3 matches) → France / National 2 - Group A
UPDATE matches        SET league_id = 'a8a0176e-027d-4ec1-887f-137245a0d813' WHERE league_id = '190c6f62-5bab-42bf-b124-04f79a167682';
UPDATE seasons        SET league_id = 'a8a0176e-027d-4ec1-887f-137245a0d813' WHERE league_id = '190c6f62-5bab-42bf-b124-04f79a167682';
UPDATE model_evaluations SET league_id = 'a8a0176e-027d-4ec1-887f-137245a0d813' WHERE league_id = '190c6f62-5bab-42bf-b124-04f79a167682';
DELETE FROM leagues   WHERE id = '190c6f62-5bab-42bf-b124-04f79a167682';

-- France / National 2 Group B (4 matches) → France / National 2 - Group B
UPDATE matches        SET league_id = 'da90d223-0909-48ea-8fa4-c15f729c6044' WHERE league_id = '209f0f46-b8cc-4f92-bfb5-a239b773dd66';
UPDATE seasons        SET league_id = 'da90d223-0909-48ea-8fa4-c15f729c6044' WHERE league_id = '209f0f46-b8cc-4f92-bfb5-a239b773dd66';
UPDATE model_evaluations SET league_id = 'da90d223-0909-48ea-8fa4-c15f729c6044' WHERE league_id = '209f0f46-b8cc-4f92-bfb5-a239b773dd66';
DELETE FROM leagues   WHERE id = '209f0f46-b8cc-4f92-bfb5-a239b773dd66';

-- France / National 2 Group C (1 matches) → France / National 2 - Group C
UPDATE matches        SET league_id = 'fe74882f-c4c2-4177-b347-63f1d8550633' WHERE league_id = '6120f4e4-0dae-4d1d-9558-d33501e1614e';
UPDATE seasons        SET league_id = 'fe74882f-c4c2-4177-b347-63f1d8550633' WHERE league_id = '6120f4e4-0dae-4d1d-9558-d33501e1614e';
UPDATE model_evaluations SET league_id = 'fe74882f-c4c2-4177-b347-63f1d8550633' WHERE league_id = '6120f4e4-0dae-4d1d-9558-d33501e1614e';
DELETE FROM leagues   WHERE id = '6120f4e4-0dae-4d1d-9558-d33501e1614e';

-- Italy / Campionato Primavera 2 (1 matches) → Italy / Campionato Primavera - 2
UPDATE matches        SET league_id = '24a45c29-b2e4-4620-97ee-11de7e09dc63' WHERE league_id = 'a5eb3e01-48fe-4b64-bd72-6be00d235d6a';
UPDATE seasons        SET league_id = '24a45c29-b2e4-4620-97ee-11de7e09dc63' WHERE league_id = 'a5eb3e01-48fe-4b64-bd72-6be00d235d6a';
UPDATE model_evaluations SET league_id = '24a45c29-b2e4-4620-97ee-11de7e09dc63' WHERE league_id = 'a5eb3e01-48fe-4b64-bd72-6be00d235d6a';
DELETE FROM leagues   WHERE id = 'a5eb3e01-48fe-4b64-bd72-6be00d235d6a';

-- Mexico / Liga de Expansion MX (2 matches) → Mexico / Liga de Expansión MX
UPDATE matches        SET league_id = '179d1e47-6bba-4c77-980e-473755f38750' WHERE league_id = '4c354ebd-15d1-4b2b-8a01-4580615130be';
UPDATE seasons        SET league_id = '179d1e47-6bba-4c77-980e-473755f38750' WHERE league_id = '4c354ebd-15d1-4b2b-8a01-4580615130be';
UPDATE model_evaluations SET league_id = '179d1e47-6bba-4c77-980e-473755f38750' WHERE league_id = '4c354ebd-15d1-4b2b-8a01-4580615130be';
DELETE FROM leagues   WHERE id = '4c354ebd-15d1-4b2b-8a01-4580615130be';

-- Portugal / Taça Revelacao U23 (2 matches) → Portugal / Taça Revelação U23
UPDATE matches        SET league_id = 'c98776a4-7efc-4ce7-9281-721e84104f83' WHERE league_id = '3eae34f7-bd53-405c-838b-889944d2f7a5';
UPDATE seasons        SET league_id = 'c98776a4-7efc-4ce7-9281-721e84104f83' WHERE league_id = '3eae34f7-bd53-405c-838b-889944d2f7a5';
UPDATE model_evaluations SET league_id = 'c98776a4-7efc-4ce7-9281-721e84104f83' WHERE league_id = '3eae34f7-bd53-405c-838b-889944d2f7a5';
DELETE FROM leagues   WHERE id = '3eae34f7-bd53-405c-838b-889944d2f7a5';

-- Slovakia / 2. Liga (4 matches) → Slovakia / 2. liga
UPDATE matches        SET league_id = '186abd82-4e60-49de-b38b-7b7a756049b3' WHERE league_id = 'e4c92da1-123f-4184-9483-f46d40a19790';
UPDATE seasons        SET league_id = '186abd82-4e60-49de-b38b-7b7a756049b3' WHERE league_id = 'e4c92da1-123f-4184-9483-f46d40a19790';
UPDATE model_evaluations SET league_id = '186abd82-4e60-49de-b38b-7b7a756049b3' WHERE league_id = 'e4c92da1-123f-4184-9483-f46d40a19790';
DELETE FROM leagues   WHERE id = 'e4c92da1-123f-4184-9483-f46d40a19790';

-- South Africa / Diski Challenge (4 matches) → South-Africa / Diski Challenge
UPDATE matches        SET league_id = '975ac0a1-f58c-4069-9a7a-7854db5787fe' WHERE league_id = '9b892a54-8de2-43dc-8b35-fa7b5aad1b7c';
UPDATE seasons        SET league_id = '975ac0a1-f58c-4069-9a7a-7854db5787fe' WHERE league_id = '9b892a54-8de2-43dc-8b35-fa7b5aad1b7c';
UPDATE model_evaluations SET league_id = '975ac0a1-f58c-4069-9a7a-7854db5787fe' WHERE league_id = '9b892a54-8de2-43dc-8b35-fa7b5aad1b7c';
DELETE FROM leagues   WHERE id = '9b892a54-8de2-43dc-8b35-fa7b5aad1b7c';

-- South Korea / K-3 League (7 matches) → South-Korea / K3 League
UPDATE matches        SET league_id = '2425baed-e4df-4b6d-97cd-dac30f8f68b9' WHERE league_id = '3d5abc68-43ad-4e89-ad04-e9f58d42bb2f';
UPDATE seasons        SET league_id = '2425baed-e4df-4b6d-97cd-dac30f8f68b9' WHERE league_id = '3d5abc68-43ad-4e89-ad04-e9f58d42bb2f';
UPDATE model_evaluations SET league_id = '2425baed-e4df-4b6d-97cd-dac30f8f68b9' WHERE league_id = '3d5abc68-43ad-4e89-ad04-e9f58d42bb2f';
DELETE FROM leagues   WHERE id = '3d5abc68-43ad-4e89-ad04-e9f58d42bb2f';

-- South Korea / K-League 1 (6 matches) → South-Korea / K League 1
UPDATE matches        SET league_id = '9c8e4836-482a-43fa-abc1-be203ca12341' WHERE league_id = 'aa2d789b-8c7b-4943-998b-d70b676f14da';
UPDATE seasons        SET league_id = '9c8e4836-482a-43fa-abc1-be203ca12341' WHERE league_id = 'aa2d789b-8c7b-4943-998b-d70b676f14da';
UPDATE model_evaluations SET league_id = '9c8e4836-482a-43fa-abc1-be203ca12341' WHERE league_id = 'aa2d789b-8c7b-4943-998b-d70b676f14da';
DELETE FROM leagues   WHERE id = 'aa2d789b-8c7b-4943-998b-d70b676f14da';

-- Sweden / Ettan Norra (5 matches) → Sweden / Ettan - Norra
UPDATE matches        SET league_id = '0bcf80ef-8787-4194-9cab-3b3f39fb61c9' WHERE league_id = 'f3f9d31c-8e5d-45f1-b3d3-df1a2a599bb2';
UPDATE seasons        SET league_id = '0bcf80ef-8787-4194-9cab-3b3f39fb61c9' WHERE league_id = 'f3f9d31c-8e5d-45f1-b3d3-df1a2a599bb2';
UPDATE model_evaluations SET league_id = '0bcf80ef-8787-4194-9cab-3b3f39fb61c9' WHERE league_id = 'f3f9d31c-8e5d-45f1-b3d3-df1a2a599bb2';
DELETE FROM leagues   WHERE id = 'f3f9d31c-8e5d-45f1-b3d3-df1a2a599bb2';

-- Sweden / Ettan Södra (8 matches) → Sweden / Ettan - Södra
UPDATE matches        SET league_id = '99b81d2e-a0ef-48af-8468-25af6feafdb0' WHERE league_id = 'b7765fcb-bf39-4c21-9cd0-fdbcfe17d9f2';
UPDATE seasons        SET league_id = '99b81d2e-a0ef-48af-8468-25af6feafdb0' WHERE league_id = 'b7765fcb-bf39-4c21-9cd0-fdbcfe17d9f2';
UPDATE model_evaluations SET league_id = '99b81d2e-a0ef-48af-8468-25af6feafdb0' WHERE league_id = 'b7765fcb-bf39-4c21-9cd0-fdbcfe17d9f2';
DELETE FROM leagues   WHERE id = 'b7765fcb-bf39-4c21-9cd0-fdbcfe17d9f2';

-- United Arab Emirates / League Cup (1 matches) → United-Arab-Emirates / League Cup
UPDATE matches        SET league_id = '9d3ace64-e931-4ba0-bb4d-d069c5df9b45' WHERE league_id = '85a9b9ec-285e-4284-aa2b-59238fd1d084';
UPDATE seasons        SET league_id = '9d3ace64-e931-4ba0-bb4d-d069c5df9b45' WHERE league_id = '85a9b9ec-285e-4284-aa2b-59238fd1d084';
UPDATE model_evaluations SET league_id = '9d3ace64-e931-4ba0-bb4d-d069c5df9b45' WHERE league_id = '85a9b9ec-285e-4284-aa2b-59238fd1d084';
DELETE FROM leagues   WHERE id = '85a9b9ec-285e-4284-aa2b-59238fd1d084';

-- Uruguay / Segunda Division (2 matches) → Uruguay / Segunda División
UPDATE matches        SET league_id = '9bdcc38e-23d0-4b78-89b5-65bd522cf2ea' WHERE league_id = 'e52261a4-f71f-400f-865c-ddec720eae38';
UPDATE seasons        SET league_id = '9bdcc38e-23d0-4b78-89b5-65bd522cf2ea' WHERE league_id = 'e52261a4-f71f-400f-865c-ddec720eae38';
UPDATE model_evaluations SET league_id = '9bdcc38e-23d0-4b78-89b5-65bd522cf2ea' WHERE league_id = 'e52261a4-f71f-400f-865c-ddec720eae38';
DELETE FROM leagues   WHERE id = 'e52261a4-f71f-400f-865c-ddec720eae38';

-- ============================================================
-- 2. Merge duplicate teams (same normalised name/country)
-- ============================================================

-- Qatar: 'Al Duhail SC' (3 matches) → 'Al-Duhail SC' (3 matches)
UPDATE matches        SET home_team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE home_team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
UPDATE matches        SET away_team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE away_team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
UPDATE lineups        SET team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
UPDATE players        SET team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
UPDATE manager_tenures SET team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
UPDATE team_transfers  SET team_id = '01bda5be-0540-43d3-821e-eddb17ca23ba' WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
DELETE FROM team_elo_daily  WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
DELETE FROM team_form_cache WHERE team_id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';
DELETE FROM teams           WHERE id = 'b6b108a8-aaf3-4618-8066-8c23169a704a';

-- Sweden: 'Mjällby AIF' (1 matches) → 'Mjallby AIF' (3 matches)
UPDATE matches        SET home_team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE home_team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
UPDATE matches        SET away_team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE away_team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
UPDATE lineups        SET team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
UPDATE players        SET team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
UPDATE manager_tenures SET team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
UPDATE team_transfers  SET team_id = '620e4fbc-9bf7-4781-9739-3d1e37859bd3' WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
DELETE FROM team_elo_daily  WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
DELETE FROM team_form_cache WHERE team_id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';
DELETE FROM teams           WHERE id = '028bcc86-d392-4cdb-a2ec-4f565afecfcd';

-- Poland: 'Górnik Zabrze' (1 matches) → 'Gornik Zabrze' (2 matches)
UPDATE matches        SET home_team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE home_team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
UPDATE matches        SET away_team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE away_team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
UPDATE lineups        SET team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
UPDATE players        SET team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
UPDATE manager_tenures SET team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
UPDATE team_transfers  SET team_id = 'ccf61d44-3193-4faa-9a7e-354c8594040b' WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
DELETE FROM team_elo_daily  WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
DELETE FROM team_form_cache WHERE team_id = '03897f94-c675-4f8e-addb-4695de9e2c18';
DELETE FROM teams           WHERE id = '03897f94-c675-4f8e-addb-4695de9e2c18';

-- Sweden: 'Åtvidabergs FF' (1 matches) → 'Atvidabergs FF' (2 matches)
UPDATE matches        SET home_team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE home_team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
UPDATE matches        SET away_team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE away_team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
UPDATE lineups        SET team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
UPDATE players        SET team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
UPDATE manager_tenures SET team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
UPDATE team_transfers  SET team_id = 'f7b56c0e-5397-4d2e-bb48-ac197ae4d1f7' WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
DELETE FROM team_elo_daily  WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
DELETE FROM team_form_cache WHERE team_id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';
DELETE FROM teams           WHERE id = '09f7d0f7-2de6-4e6f-8a81-9ad9d9a2af99';

-- Bahrain: 'Al Hidd' (1 matches) → 'Al-Hidd' (3 matches)
UPDATE matches        SET home_team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE home_team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
UPDATE matches        SET away_team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE away_team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
UPDATE lineups        SET team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
UPDATE players        SET team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
UPDATE manager_tenures SET team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
UPDATE team_transfers  SET team_id = '879fb3e0-bafd-46d3-a0cf-26230c8efc5b' WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
DELETE FROM team_elo_daily  WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
DELETE FROM team_form_cache WHERE team_id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';
DELETE FROM teams           WHERE id = '0cdccc0e-f12d-43c0-8b05-192e9fb85583';

-- Turkey: 'Kucukcekmece Sinop Spor' (1 matches) → 'Küçükçekmece Sinopspor' (2 matches)
UPDATE matches        SET home_team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE home_team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
UPDATE matches        SET away_team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE away_team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
UPDATE lineups        SET team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
UPDATE players        SET team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
UPDATE manager_tenures SET team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
UPDATE team_transfers  SET team_id = '10cf9d8b-8fa6-47bd-acc5-ee6e5652a95b' WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
DELETE FROM team_elo_daily  WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
DELETE FROM team_form_cache WHERE team_id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';
DELETE FROM teams           WHERE id = 'f2ee1ffc-7e66-4be0-9242-e6d707d39a9b';

-- Saudi-Arabia: 'Al Ula' (2 matches) → 'AlUla' (2 matches)
UPDATE matches        SET home_team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE home_team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
UPDATE matches        SET away_team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE away_team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
UPDATE lineups        SET team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
UPDATE players        SET team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
UPDATE manager_tenures SET team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
UPDATE team_transfers  SET team_id = 'c047d3e6-cdac-495a-9129-b5c13a3793dc' WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
DELETE FROM team_elo_daily  WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
DELETE FROM team_form_cache WHERE team_id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';
DELETE FROM teams           WHERE id = '119a0b9f-2fd5-4178-beaf-9c145744ec1a';

-- Turkey: 'Corluspor 1947' (1 matches) → 'Çorluspor 1947' (2 matches)
UPDATE matches        SET home_team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE home_team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
UPDATE matches        SET away_team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE away_team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
UPDATE lineups        SET team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
UPDATE players        SET team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
UPDATE manager_tenures SET team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
UPDATE team_transfers  SET team_id = '6191c125-afc0-4735-bdf1-651e6ad56345' WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
DELETE FROM team_elo_daily  WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
DELETE FROM team_form_cache WHERE team_id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';
DELETE FROM teams           WHERE id = '15486bb2-e4d4-4963-ae95-73f25ac3f6b9';

-- Germany: 'Augsburg U19' (1 matches) → 'Augsburg U19' (1 matches)
UPDATE matches        SET home_team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE home_team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
UPDATE matches        SET away_team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE away_team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
UPDATE lineups        SET team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
UPDATE players        SET team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
UPDATE manager_tenures SET team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
UPDATE team_transfers  SET team_id = '16cc4701-46cb-47de-af7f-f16c72a87152' WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
DELETE FROM team_elo_daily  WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
DELETE FROM team_form_cache WHERE team_id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';
DELETE FROM teams           WHERE id = '1db84ae4-d2e1-42b2-91b6-9e8b2ce4f778';

-- Turkey: 'İstanbulspor' (1 matches) → 'Istanbulspor' (1 matches)
UPDATE matches        SET home_team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE home_team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
UPDATE matches        SET away_team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE away_team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
UPDATE lineups        SET team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
UPDATE players        SET team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
UPDATE manager_tenures SET team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
UPDATE team_transfers  SET team_id = '1ba30b3e-3593-464a-84ac-cb887260267a' WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
DELETE FROM team_elo_daily  WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
DELETE FROM team_form_cache WHERE team_id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';
DELETE FROM teams           WHERE id = 'ca2a9404-8cd2-4e2b-84ea-292329c88349';

-- Spain: 'Yeclano II' (1 matches) → 'Yeclano II' (3 matches)
UPDATE matches        SET home_team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE home_team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
UPDATE matches        SET away_team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE away_team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
UPDATE lineups        SET team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
UPDATE players        SET team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
UPDATE manager_tenures SET team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
UPDATE team_transfers  SET team_id = 'b7a2871a-09fb-4919-9e98-539362de2aaf' WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
DELETE FROM team_elo_daily  WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
DELETE FROM team_form_cache WHERE team_id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';
DELETE FROM teams           WHERE id = '1f9fa1ec-0596-4a25-925e-8e2ab9f45417';

-- Turkey: 'Keciörengücü' (1 matches) → 'Keçiörengücü' (1 matches)
UPDATE matches        SET home_team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE home_team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
UPDATE matches        SET away_team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE away_team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
UPDATE lineups        SET team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
UPDATE players        SET team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
UPDATE manager_tenures SET team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
UPDATE team_transfers  SET team_id = '1fec92e5-f4dd-4971-9ae5-c528d4160288' WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
DELETE FROM team_elo_daily  WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
DELETE FROM team_form_cache WHERE team_id = 'e08f7319-bef1-4b62-acc0-b136bf889552';
DELETE FROM teams           WHERE id = 'e08f7319-bef1-4b62-acc0-b136bf889552';

-- Italy: 'Sudtirol' (1 matches) → 'Südtirol' (1 matches)
UPDATE matches        SET home_team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE home_team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
UPDATE matches        SET away_team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE away_team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
UPDATE lineups        SET team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
UPDATE players        SET team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
UPDATE manager_tenures SET team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
UPDATE team_transfers  SET team_id = '1ffbcfe8-02bb-4173-8165-344f25f7602f' WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
DELETE FROM team_elo_daily  WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
DELETE FROM team_form_cache WHERE team_id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';
DELETE FROM teams           WHERE id = 'a7f16af4-923e-4e86-9f46-ddb25710c1bc';

-- Hungary: 'Diósgyőri VTK' (1 matches) → 'Diosgyori VTK' (1 matches)
UPDATE matches        SET home_team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE home_team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
UPDATE matches        SET away_team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE away_team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
UPDATE lineups        SET team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
UPDATE players        SET team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
UPDATE manager_tenures SET team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
UPDATE team_transfers  SET team_id = '27660a08-123f-44cd-aa09-df3ff38d85e3' WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
DELETE FROM team_elo_daily  WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
DELETE FROM team_form_cache WHERE team_id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';
DELETE FROM teams           WHERE id = 'bd17e4d4-9bc7-4ba1-a774-ab57053ddb98';

-- Lithuania: 'Sūduva Marijampolė' (2 matches) → 'Suduva Marijampole' (4 matches)
UPDATE matches        SET home_team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE home_team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
UPDATE matches        SET away_team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE away_team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
UPDATE lineups        SET team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
UPDATE players        SET team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
UPDATE manager_tenures SET team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
UPDATE team_transfers  SET team_id = '276e12a5-fb01-42a1-9539-5153bb171dc2' WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
DELETE FROM team_elo_daily  WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
DELETE FROM team_form_cache WHERE team_id = 'aa602764-8956-4ba0-a45d-49358d7b5703';
DELETE FROM teams           WHERE id = 'aa602764-8956-4ba0-a45d-49358d7b5703';

-- Iceland: 'ÍA Akranes' (1 matches) → 'IA Akranes' (4 matches)
UPDATE matches        SET home_team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE home_team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
UPDATE matches        SET away_team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE away_team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
UPDATE lineups        SET team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
UPDATE players        SET team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
UPDATE manager_tenures SET team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
UPDATE team_transfers  SET team_id = '34d8adfa-1e11-4246-8144-9c9bc4cbc76b' WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
DELETE FROM team_elo_daily  WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
DELETE FROM team_form_cache WHERE team_id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';
DELETE FROM teams           WHERE id = '3f6ec1fb-8c5b-4b01-86c5-924179f47552';

-- Liberia: 'Downtown' (1 matches) → 'Downtown' (1 matches)
UPDATE matches        SET home_team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE home_team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
UPDATE matches        SET away_team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE away_team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
UPDATE lineups        SET team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
UPDATE players        SET team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
UPDATE manager_tenures SET team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
UPDATE team_transfers  SET team_id = '3732f4ff-2736-4327-b880-863447669311' WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
DELETE FROM team_elo_daily  WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
DELETE FROM team_form_cache WHERE team_id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';
DELETE FROM teams           WHERE id = '78d01e95-4eaa-476e-aaa8-f27dbbc30439';

-- Saudi Arabia: 'Al-Jubail' (1 matches) → 'Al Jubail' (1 matches)
UPDATE matches        SET home_team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE home_team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
UPDATE matches        SET away_team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE away_team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
UPDATE lineups        SET team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
UPDATE players        SET team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
UPDATE manager_tenures SET team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
UPDATE team_transfers  SET team_id = '38aa0cbb-4b03-4d92-948d-6850e3c8f0cc' WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
DELETE FROM team_elo_daily  WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
DELETE FROM team_form_cache WHERE team_id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';
DELETE FROM teams           WHERE id = '9905ea93-ce63-47f1-bbdb-d97e086cf004';

-- Qatar: 'Al-Markhiya' (1 matches) → 'Al Markhiya' (1 matches)
UPDATE matches        SET home_team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE home_team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
UPDATE matches        SET away_team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE away_team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
UPDATE lineups        SET team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
UPDATE players        SET team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
UPDATE manager_tenures SET team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
UPDATE team_transfers  SET team_id = '3b1ee90e-5b22-4634-9237-27214e0c8b96' WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
DELETE FROM team_elo_daily  WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
DELETE FROM team_form_cache WHERE team_id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';
DELETE FROM teams           WHERE id = 'a7fb6023-bcf2-4ac8-8de1-e687ab2e7643';

-- Iceland: 'IR Reykjavik' (1 matches) → 'ÍR Reykjavík' (1 matches)
UPDATE matches        SET home_team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE home_team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
UPDATE matches        SET away_team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE away_team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
UPDATE lineups        SET team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
UPDATE players        SET team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
UPDATE manager_tenures SET team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
UPDATE team_transfers  SET team_id = '3b898e95-e637-46a9-b9e6-af095dd6b53d' WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
DELETE FROM team_elo_daily  WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
DELETE FROM team_form_cache WHERE team_id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';
DELETE FROM teams           WHERE id = 'a2276dfa-9464-4f45-be52-363e8d35e85e';

-- Iraq: 'AL Karma' (1 matches) → 'Al-Karma' (3 matches)
UPDATE matches        SET home_team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE home_team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
UPDATE matches        SET away_team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE away_team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
UPDATE lineups        SET team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
UPDATE players        SET team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
UPDATE manager_tenures SET team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
UPDATE team_transfers  SET team_id = '3c5b3539-7330-469a-90c3-d26076ffb9fd' WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
DELETE FROM team_elo_daily  WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
DELETE FROM team_form_cache WHERE team_id = '5b006a6d-076b-40ea-884a-979eeac5f93c';
DELETE FROM teams           WHERE id = '5b006a6d-076b-40ea-884a-979eeac5f93c';

-- Peru: 'César Vallejo' (1 matches) → 'Cesar Vallejo' (3 matches)
UPDATE matches        SET home_team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE home_team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
UPDATE matches        SET away_team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE away_team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
UPDATE lineups        SET team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
UPDATE players        SET team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
UPDATE manager_tenures SET team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
UPDATE team_transfers  SET team_id = '8f37db5b-5727-47c8-a085-13dfc8df2904' WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
DELETE FROM team_elo_daily  WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
DELETE FROM team_form_cache WHERE team_id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';
DELETE FROM teams           WHERE id = '3cf8f047-dee4-4ceb-a572-e26a09f806e3';

-- Sweden: 'Ängelholms FF' (1 matches) → 'Angelholms FF' (2 matches)
UPDATE matches        SET home_team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE home_team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
UPDATE matches        SET away_team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE away_team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
UPDATE lineups        SET team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
UPDATE players        SET team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
UPDATE manager_tenures SET team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
UPDATE team_transfers  SET team_id = '4044dd40-59c9-4083-af8f-d8eb8bc947d9' WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
DELETE FROM team_elo_daily  WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
DELETE FROM team_form_cache WHERE team_id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';
DELETE FROM teams           WHERE id = 'bd189fb8-4f33-4a48-9e09-eb97504e0823';

-- Saudi Arabia: 'Al Raed' (2 matches) → 'Al-Raed' (2 matches)
UPDATE matches        SET home_team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE home_team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
UPDATE matches        SET away_team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE away_team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
UPDATE lineups        SET team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
UPDATE players        SET team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
UPDATE manager_tenures SET team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
UPDATE team_transfers  SET team_id = '413a5a6d-21b0-49cf-9083-d9531caddb44' WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
DELETE FROM team_elo_daily  WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
DELETE FROM team_form_cache WHERE team_id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';
DELETE FROM teams           WHERE id = 'f5a8ecca-d3d9-46de-8eae-ebefbc6ddb13';

-- Saudi Arabia: 'Al Fateh' (2 matches) → 'Al-Fateh' (4 matches)
UPDATE matches        SET home_team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE home_team_id = '441de2a4-eea4-42c1-9619-86814d644692';
UPDATE matches        SET away_team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE away_team_id = '441de2a4-eea4-42c1-9619-86814d644692';
UPDATE lineups        SET team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
UPDATE players        SET team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
UPDATE manager_tenures SET team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
UPDATE team_transfers  SET team_id = 'fa54be98-0cb5-49e5-b0ea-1da4dc55ef8f' WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
DELETE FROM team_elo_daily  WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
DELETE FROM team_form_cache WHERE team_id = '441de2a4-eea4-42c1-9619-86814d644692';
DELETE FROM teams           WHERE id = '441de2a4-eea4-42c1-9619-86814d644692';

-- Sweden: 'Örebro SK' (1 matches) → 'Orebro SK' (1 matches)
UPDATE matches        SET home_team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE home_team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
UPDATE matches        SET away_team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE away_team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
UPDATE lineups        SET team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
UPDATE players        SET team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
UPDATE manager_tenures SET team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
UPDATE team_transfers  SET team_id = '47b9386e-cee7-4d43-8676-bc301e02a414' WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
DELETE FROM team_elo_daily  WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
DELETE FROM team_form_cache WHERE team_id = '72e596af-5f96-450e-8dc9-16950f4e4623';
DELETE FROM teams           WHERE id = '72e596af-5f96-450e-8dc9-16950f4e4623';

-- Liberia: 'Black Man Warrior' (1 matches) → 'Black Man Warrior' (1 matches)
UPDATE matches        SET home_team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE home_team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
UPDATE matches        SET away_team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE away_team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
UPDATE lineups        SET team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
UPDATE players        SET team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
UPDATE manager_tenures SET team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
UPDATE team_transfers  SET team_id = '493eb4c0-1495-4ad8-8b84-6a22231ce805' WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
DELETE FROM team_elo_daily  WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
DELETE FROM team_form_cache WHERE team_id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';
DELETE FROM teams           WHERE id = 'b6f60dd7-9507-42ca-9dc2-588380764cfd';

-- Sweden: 'Örgryte IS' (1 matches) → 'Orgryte IS' (2 matches)
UPDATE matches        SET home_team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE home_team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
UPDATE matches        SET away_team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE away_team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
UPDATE lineups        SET team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
UPDATE players        SET team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
UPDATE manager_tenures SET team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
UPDATE team_transfers  SET team_id = 'e94af25b-3fcf-4fa7-894c-29f0e6d0b5da' WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
DELETE FROM team_elo_daily  WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
DELETE FROM team_form_cache WHERE team_id = '49ee95ff-886e-431c-bd31-d73e69bd5266';
DELETE FROM teams           WHERE id = '49ee95ff-886e-431c-bd31-d73e69bd5266';

-- Qatar: 'Al-Sailiya' (1 matches) → 'Al Sailiya' (1 matches)
UPDATE matches        SET home_team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE home_team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
UPDATE matches        SET away_team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE away_team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
UPDATE lineups        SET team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
UPDATE players        SET team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
UPDATE manager_tenures SET team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
UPDATE team_transfers  SET team_id = '503531ec-4ba6-4ef2-bed1-a5ded9d33207' WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
DELETE FROM team_elo_daily  WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
DELETE FROM team_form_cache WHERE team_id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';
DELETE FROM teams           WHERE id = 'a1621d9b-75e1-4db8-b144-271171ec38f5';

-- Oman: 'Al Seeb' (1 matches) → 'Al-Seeb' (1 matches)
UPDATE matches        SET home_team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE home_team_id = '5d47f111-163e-4860-a015-23ec716d922a';
UPDATE matches        SET away_team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE away_team_id = '5d47f111-163e-4860-a015-23ec716d922a';
UPDATE lineups        SET team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
UPDATE players        SET team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
UPDATE manager_tenures SET team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
UPDATE team_transfers  SET team_id = '53f13d55-113b-4f21-b124-06961de83dd2' WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
DELETE FROM team_elo_daily  WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
DELETE FROM team_form_cache WHERE team_id = '5d47f111-163e-4860-a015-23ec716d922a';
DELETE FROM teams           WHERE id = '5d47f111-163e-4860-a015-23ec716d922a';

-- Liberia: 'Fassell' (1 matches) → 'Fassell' (1 matches)
UPDATE matches        SET home_team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE home_team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
UPDATE matches        SET away_team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE away_team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
UPDATE lineups        SET team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
UPDATE players        SET team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
UPDATE manager_tenures SET team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
UPDATE team_transfers  SET team_id = '5529599d-4890-4f00-b545-7af615fbb385' WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
DELETE FROM team_elo_daily  WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
DELETE FROM team_form_cache WHERE team_id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';
DELETE FROM teams           WHERE id = '9881fcb4-12f5-486c-bfdd-73ebe972188e';

-- Hungary: 'Győri ETO FC' (1 matches) → 'Gyori ETO FC' (1 matches)
UPDATE matches        SET home_team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE home_team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
UPDATE matches        SET away_team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE away_team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
UPDATE lineups        SET team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
UPDATE players        SET team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
UPDATE manager_tenures SET team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
UPDATE team_transfers  SET team_id = '58f5f914-c039-43ab-9399-3c047327d18c' WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
DELETE FROM team_elo_daily  WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
DELETE FROM team_form_cache WHERE team_id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';
DELETE FROM teams           WHERE id = 'b08063b6-c5b9-4915-a94f-816b8d854fd1';

-- Japan: 'Júbilo Iwata' (2 matches) → 'Jubilo Iwata' (4 matches)
UPDATE matches        SET home_team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE home_team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
UPDATE matches        SET away_team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE away_team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
UPDATE lineups        SET team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
UPDATE players        SET team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
UPDATE manager_tenures SET team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
UPDATE team_transfers  SET team_id = '92163fd1-0da9-4cff-bbd7-3cce88815021' WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
DELETE FROM team_elo_daily  WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
DELETE FROM team_form_cache WHERE team_id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';
DELETE FROM teams           WHERE id = '5a336d1d-41fa-4055-b5f9-3293b90678f8';

-- Iceland: 'Fjölnir' (1 matches) → 'Fjolnir' (2 matches)
UPDATE matches        SET home_team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE home_team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
UPDATE matches        SET away_team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE away_team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
UPDATE lineups        SET team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
UPDATE players        SET team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
UPDATE manager_tenures SET team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
UPDATE team_transfers  SET team_id = 'dce56ae8-bea7-4616-8e84-cff2eec00065' WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
DELETE FROM team_elo_daily  WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
DELETE FROM team_form_cache WHERE team_id = '683f3b28-efe6-4599-878a-5f26f53e1486';
DELETE FROM teams           WHERE id = '683f3b28-efe6-4599-878a-5f26f53e1486';

-- Qatar: 'Al Khor' (1 matches) → 'Al-Khor' (1 matches)
UPDATE matches        SET home_team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE home_team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
UPDATE matches        SET away_team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE away_team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
UPDATE lineups        SET team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
UPDATE players        SET team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
UPDATE manager_tenures SET team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
UPDATE team_transfers  SET team_id = '69338e6c-2d8b-48b6-b0ac-501b8e53894d' WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
DELETE FROM team_elo_daily  WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
DELETE FROM team_form_cache WHERE team_id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';
DELETE FROM teams           WHERE id = 'd64b4ef2-5f57-4840-a5db-49bc41260e07';

-- Slovakia: 'Slavia Tu Kosice' (1 matches) → 'Slávia TU Košice' (1 matches)
UPDATE matches        SET home_team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE home_team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
UPDATE matches        SET away_team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE away_team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
UPDATE lineups        SET team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
UPDATE players        SET team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
UPDATE manager_tenures SET team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
UPDATE team_transfers  SET team_id = '69364f4d-c3d8-4ad6-98f4-a57ed05efa3a' WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
DELETE FROM team_elo_daily  WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
DELETE FROM team_form_cache WHERE team_id = '711a232b-5989-46ea-a3c9-cf30c3543f16';
DELETE FROM teams           WHERE id = '711a232b-5989-46ea-a3c9-cf30c3543f16';

-- Spain: 'Unión Molinense' (1 matches) → 'Unión Molinense' (3 matches)
UPDATE matches        SET home_team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE home_team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
UPDATE matches        SET away_team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE away_team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
UPDATE lineups        SET team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
UPDATE players        SET team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
UPDATE manager_tenures SET team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
UPDATE team_transfers  SET team_id = '77ae0c10-51cd-4c65-b65a-72cded0603d1' WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
DELETE FROM team_elo_daily  WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
DELETE FROM team_form_cache WHERE team_id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';
DELETE FROM teams           WHERE id = '6a7a1726-f8c0-4659-88e9-e8f12ef1e0d3';

-- Germany: 'Wolfsburg U19' (1 matches) → 'Wolfsburg U19' (2 matches)
UPDATE matches        SET home_team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE home_team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
UPDATE matches        SET away_team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE away_team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
UPDATE lineups        SET team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
UPDATE players        SET team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
UPDATE manager_tenures SET team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
UPDATE team_transfers  SET team_id = '75696aee-d610-44f4-9df3-c4fb02caad06' WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
DELETE FROM team_elo_daily  WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
DELETE FROM team_form_cache WHERE team_id = 'a4727782-4002-4c54-859b-e10d63663fea';
DELETE FROM teams           WHERE id = 'a4727782-4002-4c54-859b-e10d63663fea';

-- Norway: 'Åsane' (1 matches) → 'Asane' (2 matches)
UPDATE matches        SET home_team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE home_team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
UPDATE matches        SET away_team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE away_team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
UPDATE lineups        SET team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
UPDATE players        SET team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
UPDATE manager_tenures SET team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
UPDATE team_transfers  SET team_id = 'e9cd3429-4a5d-4d66-9f79-ba728ae06930' WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
DELETE FROM team_elo_daily  WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
DELETE FROM team_form_cache WHERE team_id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';
DELETE FROM teams           WHERE id = '79d2be3c-89fa-498d-a9a2-88bcbfd14cea';

-- Liberia: 'Borough' (1 matches) → 'Borough' (2 matches)
UPDATE matches        SET home_team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE home_team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
UPDATE matches        SET away_team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE away_team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
UPDATE lineups        SET team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
UPDATE players        SET team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
UPDATE manager_tenures SET team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
UPDATE team_transfers  SET team_id = 'f3b96f3e-ff92-44bf-8822-a3c146efcb1d' WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
DELETE FROM team_elo_daily  WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
DELETE FROM team_form_cache WHERE team_id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';
DELETE FROM teams           WHERE id = '7d7e58fb-10c8-4352-8727-bf237a6b7c37';

-- Germany: 'Paderborn U19' (1 matches) → 'Paderborn U19' (2 matches)
UPDATE matches        SET home_team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE home_team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
UPDATE matches        SET away_team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE away_team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
UPDATE lineups        SET team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
UPDATE players        SET team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
UPDATE manager_tenures SET team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
UPDATE team_transfers  SET team_id = '845d48ec-5d92-420a-9772-721851f491f8' WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
DELETE FROM team_elo_daily  WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
DELETE FROM team_form_cache WHERE team_id = 'efa2fc90-672a-44af-a049-c1298579daee';
DELETE FROM teams           WHERE id = 'efa2fc90-672a-44af-a049-c1298579daee';

-- Azerbaijan: 'Şimal' (2 matches) → 'Simal' (3 matches)
UPDATE matches        SET home_team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE home_team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
UPDATE matches        SET away_team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE away_team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
UPDATE lineups        SET team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
UPDATE players        SET team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
UPDATE manager_tenures SET team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
UPDATE team_transfers  SET team_id = '89fc1588-0440-4dac-b3d8-b4722d80c3f3' WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
DELETE FROM team_elo_daily  WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
DELETE FROM team_form_cache WHERE team_id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';
DELETE FROM teams           WHERE id = 'e13ecc58-b9e4-4a0f-b982-0f03ba898691';

-- Australia: 'St. George City FA' (1 matches) → 'St George City FA' (2 matches)
UPDATE matches        SET home_team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE home_team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
UPDATE matches        SET away_team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE away_team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
UPDATE lineups        SET team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
UPDATE players        SET team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
UPDATE manager_tenures SET team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
UPDATE team_transfers  SET team_id = '95c0b20f-2aa9-492e-af54-dc8bb794614d' WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
DELETE FROM team_elo_daily  WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
DELETE FROM team_form_cache WHERE team_id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';
DELETE FROM teams           WHERE id = 'e1c35911-5eab-4a23-80ec-22ea76cbd9b2';

-- Slovakia: 'Šamorín' (1 matches) → 'Samorín' (1 matches)
UPDATE matches        SET home_team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE home_team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
UPDATE matches        SET away_team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE away_team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
UPDATE lineups        SET team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
UPDATE players        SET team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
UPDATE manager_tenures SET team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
UPDATE team_transfers  SET team_id = '9bd9be6d-b381-49da-bf28-a5f8c5f51712' WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
DELETE FROM team_elo_daily  WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
DELETE FROM team_form_cache WHERE team_id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';
DELETE FROM teams           WHERE id = 'ff21eae0-0c04-4f14-9448-791cdb32e943';

-- Iceland: 'Thór Akureyri' (2 matches) → 'Thor Akureyri' (2 matches)
UPDATE matches        SET home_team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE home_team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
UPDATE matches        SET away_team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE away_team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
UPDATE lineups        SET team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
UPDATE players        SET team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
UPDATE manager_tenures SET team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
UPDATE team_transfers  SET team_id = 'a11d0c2b-5f6a-4777-ac0e-c9be9b2d5eca' WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
DELETE FROM team_elo_daily  WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
DELETE FROM team_form_cache WHERE team_id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';
DELETE FROM teams           WHERE id = 'cdc3c2ee-9ef3-4fa6-81d5-ebc780587f7b';

-- Denmark: 'B.93' (1 matches) → 'B 93' (1 matches)
UPDATE matches        SET home_team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE home_team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
UPDATE matches        SET away_team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE away_team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
UPDATE lineups        SET team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
UPDATE players        SET team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
UPDATE manager_tenures SET team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
UPDATE team_transfers  SET team_id = 'b6c2d040-bffa-4cb6-a7a3-ee16d5890db2' WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
DELETE FROM team_elo_daily  WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
DELETE FROM team_form_cache WHERE team_id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';
DELETE FROM teams           WHERE id = 'd87797b7-97e3-4889-9b65-ff1c19f2a9cf';

-- Liberia: 'Heaven Eleven' (1 matches) → 'Heaven Eleven' (2 matches)
UPDATE matches        SET home_team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE home_team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
UPDATE matches        SET away_team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE away_team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
UPDATE lineups        SET team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
UPDATE players        SET team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
UPDATE manager_tenures SET team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
UPDATE team_transfers  SET team_id = 'd046e414-ed51-4a8f-878c-dbb34a4a7d64' WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
DELETE FROM team_elo_daily  WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
DELETE FROM team_form_cache WHERE team_id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';
DELETE FROM teams           WHERE id = 'b902fb12-aa29-493f-af31-ece91cd7dc32';

-- Liberia: 'Freeport' (1 matches) → 'Freeport' (1 matches)
UPDATE matches        SET home_team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE home_team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
UPDATE matches        SET away_team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE away_team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
UPDATE lineups        SET team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
UPDATE players        SET team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
UPDATE manager_tenures SET team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
UPDATE team_transfers  SET team_id = 'c63d0a6e-d77c-4c32-8b89-6ee10be84f8c' WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
DELETE FROM team_elo_daily  WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
DELETE FROM team_form_cache WHERE team_id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';
DELETE FROM teams           WHERE id = 'ed94b2bf-bcd7-4228-ad7c-a32b145f71cc';

-- Saudi Arabia: 'Al Ahli Jeddah' (1 matches) → 'Al-Ahli Jeddah' (3 matches)
UPDATE matches        SET home_team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE home_team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
UPDATE matches        SET away_team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE away_team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
UPDATE lineups        SET team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
UPDATE players        SET team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
UPDATE manager_tenures SET team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
UPDATE team_transfers  SET team_id = 'ee38af74-6944-4474-b2cc-f15ae9b7dc9b' WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
DELETE FROM team_elo_daily  WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
DELETE FROM team_form_cache WHERE team_id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';
DELETE FROM teams           WHERE id = 'ccc6d5eb-59df-4b8c-94ce-a693ef3f45fb';

-- France: 'Chateaubriant' (1 matches) → 'Châteaubriant' (2 matches)
UPDATE matches        SET home_team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE home_team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
UPDATE matches        SET away_team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE away_team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
UPDATE lineups        SET team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
UPDATE players        SET team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
UPDATE manager_tenures SET team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
UPDATE team_transfers  SET team_id = 'eea96782-9998-4d98-b33d-2dd2bc3488d7' WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
DELETE FROM team_elo_daily  WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
DELETE FROM team_form_cache WHERE team_id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';
DELETE FROM teams           WHERE id = 'eb20552b-bc95-45c4-90da-33b1b9088a10';

-- ============================================================
-- 3. Merge duplicate fixtures (same home+away+date)
-- NOTE: Run AFTER league + team merges above.
-- ============================================================

-- Duplicate fixture on 2026-05-04
-- Canonical: 8d6a56c4-51af-4b95-ad62-a621147a3aa9 (af_id=1544081)
-- Orphan:    06559de0-eba5-4b05-984f-77c9cc9f343a
UPDATE simulated_bets     SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE predictions        SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE odds_snapshots     SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_signals      SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_events       SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_stats        SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_weather      SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_player_stats SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_injuries     SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE live_match_snapshots SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE news_events        SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE lineups            SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE user_bets          SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_previews     SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE referee_matches    SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
UPDATE match_page_views   SET match_id = '8d6a56c4-51af-4b95-ad62-a621147a3aa9' WHERE match_id = '06559de0-eba5-4b05-984f-77c9cc9f343a';
DELETE FROM matches WHERE id = '06559de0-eba5-4b05-984f-77c9cc9f343a';

-- Duplicate fixture on 2026-05-04
-- Canonical: 7ebcc8ff-01eb-4eda-91ea-68909a130b99 (af_id=1544082)
-- Orphan:    ef70c133-4665-40e8-b5f4-b6ed8872a987
UPDATE simulated_bets     SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE predictions        SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE odds_snapshots     SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_signals      SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_events       SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_stats        SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_weather      SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_player_stats SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_injuries     SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE live_match_snapshots SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE news_events        SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE lineups            SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE user_bets          SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_previews     SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE referee_matches    SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
UPDATE match_page_views   SET match_id = '7ebcc8ff-01eb-4eda-91ea-68909a130b99' WHERE match_id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';
DELETE FROM matches WHERE id = 'ef70c133-4665-40e8-b5f4-b6ed8872a987';

-- Duplicate fixture on 2026-05-03
-- Canonical: 140d8ac8-5358-4e7c-9ad9-3c58d0b725b2 (af_id=1540817)
-- Orphan:    557b3864-0d92-4374-b54a-199b4237284b
UPDATE simulated_bets     SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE predictions        SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE odds_snapshots     SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_signals      SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_events       SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_stats        SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_weather      SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_player_stats SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_injuries     SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE live_match_snapshots SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE news_events        SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE lineups            SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE user_bets          SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_previews     SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE referee_matches    SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
UPDATE match_page_views   SET match_id = '140d8ac8-5358-4e7c-9ad9-3c58d0b725b2' WHERE match_id = '557b3864-0d92-4374-b54a-199b4237284b';
DELETE FROM matches WHERE id = '557b3864-0d92-4374-b54a-199b4237284b';

-- Duplicate fixture on 2026-05-03
-- Canonical: eae90f22-2fe9-45f1-a570-2e6bb2cf33ee (af_id=1508750)
-- Orphan:    2a3e67c9-7198-44be-9898-c5f60f3a63c2
UPDATE simulated_bets     SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE predictions        SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE odds_snapshots     SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_signals      SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_events       SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_stats        SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_weather      SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_player_stats SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_injuries     SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE live_match_snapshots SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE news_events        SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE lineups            SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE user_bets          SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_previews     SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE referee_matches    SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
UPDATE match_page_views   SET match_id = 'eae90f22-2fe9-45f1-a570-2e6bb2cf33ee' WHERE match_id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';
DELETE FROM matches WHERE id = '2a3e67c9-7198-44be-9898-c5f60f3a63c2';

-- Duplicate fixture on 2026-05-03
-- Canonical: b3f2e8b3-b86c-4890-a3cf-6fb438375a2f (af_id=1540819)
-- Orphan:    59bd5a3c-9d93-4579-bd1f-e0a5fe767032
UPDATE simulated_bets     SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE predictions        SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE odds_snapshots     SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_signals      SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_events       SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_stats        SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_weather      SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_player_stats SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_injuries     SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE live_match_snapshots SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE news_events        SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE lineups            SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE user_bets          SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_previews     SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE referee_matches    SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
UPDATE match_page_views   SET match_id = 'b3f2e8b3-b86c-4890-a3cf-6fb438375a2f' WHERE match_id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';
DELETE FROM matches WHERE id = '59bd5a3c-9d93-4579-bd1f-e0a5fe767032';

-- Duplicate fixture on 2026-05-03
-- Canonical: bc403d09-b1b2-40fe-b43d-1d39241406bb (af_id=1540818)
-- Orphan:    5e71c28c-caf3-456a-b39d-c8f063fa58e0
UPDATE simulated_bets     SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE predictions        SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE odds_snapshots     SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_signals      SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_events       SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_stats        SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_weather      SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_player_stats SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_injuries     SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE live_match_snapshots SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE news_events        SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE lineups            SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE user_bets          SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_previews     SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE referee_matches    SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
UPDATE match_page_views   SET match_id = 'bc403d09-b1b2-40fe-b43d-1d39241406bb' WHERE match_id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';
DELETE FROM matches WHERE id = '5e71c28c-caf3-456a-b39d-c8f063fa58e0';

-- Duplicate fixture on 2026-05-03
-- Canonical: bfffee0e-f3a5-413b-96a6-04d33dfa9fcc (af_id=1539806)
-- Orphan:    db3c352a-ef03-4c45-8291-523495d02e98
UPDATE simulated_bets     SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE predictions        SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE odds_snapshots     SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_signals      SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_events       SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_stats        SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_weather      SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_player_stats SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_injuries     SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE live_match_snapshots SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE news_events        SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE lineups            SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE user_bets          SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_previews     SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE referee_matches    SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
UPDATE match_page_views   SET match_id = 'bfffee0e-f3a5-413b-96a6-04d33dfa9fcc' WHERE match_id = 'db3c352a-ef03-4c45-8291-523495d02e98';
DELETE FROM matches WHERE id = 'db3c352a-ef03-4c45-8291-523495d02e98';

-- ============================================================
-- 4. Remove Kambi-sourced odds rows (ub/paf/kambi bookmakers)
-- These were redundant: AF already covers Unibet separately.
-- ============================================================

DELETE FROM odds_snapshots WHERE bookmaker IN ('ub', 'paf', 'kambi');

COMMIT;
