-- OU-CALIBRATOR-DOMAIN-MISMATCH (2026-09-13)
--
-- WHAT WAS WRONG
-- --------------
-- `scripts/fit_calibration_from_predictions.py:186` fits the O/U Platt curve on
-- `predictions.model_probability` — the RAW ensemble probability.
-- `workers/model/improvements.py:227` applies it to `shrunk`, which is
--     alpha * model_prob + (1 - alpha) * pinnacle_devig
-- and is ~90% Pinnacle once odds > 3.0 (alpha floors at 0.10 via CAL-ALPHA-ODDS).
--
-- Fitted in one domain, applied in another. The fit's own out-of-sample ECE
-- check therefore validated a function that is never executed — the exact trap
-- `_fit_platt`'s docstring already warns about for logit-vs-probability, arrived
-- at from the other direction.
--
-- WHAT IT DID
-- -----------
-- The shipped curve for under 2.5 is sigmoid(1.5258*p - 0.8341), whose ENTIRE
-- output range is [0.3028, 0.6663] with a fixed point at 0.4713. Every
-- probability below 0.4713 is inflated, and long-priced unders are all below it.
-- Measured on live rows: input spread sd 0.2209 -> output sd 0.0823 (2.7x
-- compression). `edge = cal_prob - 1/odds` therefore degenerated into "how far
-- is this price from ~0.45", which is maximised by the longest price on the
-- board, turning the 8% O/U floor into a longshot-finder.
--
-- Against 113,506 Pinnacle under-2.5 quotes on finished matches since 08-01:
--   mkt implied 0.316 -> calibrator says 0.413, ACTUAL 0.271 (reported +9.7% edge,
--   true -4.5%). The market is well calibrated; the curve is a horizontal line
--   through it.
--
-- Of 142 picks published since the fit shipped, only 2 (1%) clear their edge
-- floor without the sigmoid lift. bot_v10_all went from 14.6% O/U share and
-- +38.5% ROI (Aug 1 - Sep 2) to 69.9% O/U share and -15.0% ROI (Sep 3 - 13),
-- peak +EUR756.06 on 09-06 -> +EUR289.30, a -EUR466.76 drawdown with -EUR449.07
-- of it in week 2026-W37 alone.
--
-- WHY DELETE RATHER THAN REFIT HERE
-- ---------------------------------
-- `apply_platt` is a graceful no-op when no row exists for a market, so removing
-- these rows reverts O/U to its pre-2026-09-03 behaviour (stage-1 Pinnacle
-- shrinkage only) with no code change. A corrected refit is a separate, measured
-- decision — see scripts/ou_calibrator_backtest.py, which replays the real gate
-- under live / none / refit-on-shrunk / refit+odds arms.
--
-- REVERT: INSERT ... SELECT * FROM model_calibration_ou_domain_mismatch_backup;

BEGIN;

-- 1. Preserve the exact rows so this is one statement to undo.
CREATE TABLE IF NOT EXISTS model_calibration_ou_domain_mismatch_backup AS
SELECT * FROM model_calibration
 WHERE market IN ('over_under_25_over', 'over_under_25_under',
                  'over_under_35_over', 'over_under_35_under',
                  'over25', 'under25', 'over35', 'under35');

-- 2. Remove them. The 3.5 rows came from the same fitter on the same day with
--    the same defect (bot_ou35_model_v1 is paper, so lower urgency, but leaving
--    a known-broken curve in place would contaminate that bot's measurement too).
--    The bare `over25`/`under25`/`over35`/`under35` keys are the predictions-side
--    vocabulary; production asks for `over_under_25_over` etc, so those rows were
--    never read — removed as dead weight, not as a behaviour change.
DELETE FROM model_calibration
 WHERE market IN ('over_under_25_over', 'over_under_25_under',
                  'over_under_35_over', 'over_under_35_under',
                  'over25', 'under25', 'over35', 'under35');

-- 3. Stop real money on the O/U model bot. It has run entirely inside the broken
--    window: n=32, -EUR139.30, -43.5% ROI, CLV -5.7% (t=-4.6), and
--    PRIORITY_QUEUE's own P0 already recommends this ("no configuration of it is
--    fold-robust"). Paper generation continues so it can be re-measured post-fix.
UPDATE coolbet_placer_bots
   SET ui_place_enabled = false,
       note = 'OFF 2026-09-13 OU-CALIBRATOR-DOMAIN-MISMATCH: every pick it staked '
              'was generated by a calibrator fitted on raw ensemble probs and '
              'applied to Pinnacle-shrunk probs. n=32, -43.5% ROI, CLV -5.7% '
              '(t=-4.6). Re-enable only after a post-fix window shows positive CLV.',
       updated_at = NOW()
 WHERE bot_name = 'bot_coolbet_ou_model_v1';

COMMIT;
